- id: "NuGet:Azure.Extensions:AspNetCore.Configuration.Secrets"
  curations:
    comment: |
      Map declared license based on
      https://github.com/Azure/azure-sdk-for-net/blob/Azure.Extensions.AspNetCore.Configuration.Secrets_1.5.1/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets/1.5.1/license": "MIT"

- id: "NuGet:Azure.Extensions:AspNetCore.Configuration.Secrets"
  curations:
    comment: |
      Package resides in its own directory within the azure-sdk-for-net monorepo.
      https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets
    vcs:
      path: "sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets"
