- id: "NuGet:AWSSDK.CostExplorer:CoreCLR:[3.3.194,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/CostExplorer"
