- id: "NuGet:HotChocolate.Execution:Projections"
  curations:
    comment: |
      Map declared license based on
      https://github.com/ChilliCream/graphql-platform/blob/15.1.17/LICENSE.
    declared_license_mapping:
      "https://www.nuget.org/packages/HotChocolate.Execution.Projections/15.1.17/license": "MIT"
