---
id: "NuGet:Azure.Messaging:ServiceBus:(,7.20.2]"
path_excludes:
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*sample*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CHANGELOG*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Dockerfile"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Mocking/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Perf/**"
  reason: "TEST_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/build.proj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/package-lock.json"
  reason: "BUILD_TOOL_OF"
- pattern: "**/perf/**"
  reason: "TEST_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
