---
id: "NuGet:Microsoft.Extensions:Http:8.0.1"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime"
  revision: "81cabf2857a01351e5ab578947c7403a5b128ad1"
path_excludes:
- pattern: "tests/**"
  reason: "TEST_OF"
license_finding_curations:
- path: "src/ActiveHandlerTrackingEntry.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/DefaultHttpClientBuilderServiceCollection.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/DefaultHttpClientConfigurationTracker.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DefaultHttpClientFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DefaultHttpMessageHandlerBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/DefaultSocketsHttpHandlerBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DefaultTypedHttpClientFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ExpiredHandlerTrackingEntry.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/HttpClientBuilderExtensions.Logging.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/HttpClientBuilderExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HttpClientFactoryExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HttpClientFactoryOptions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/HttpClientLoggerHandler.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/HttpClientMappingRegistry.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/HttpHeadersLogValue.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HttpMessageHandlerBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HttpMessageHandlerFactoryExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/IHttpClientAsyncLogger.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/IHttpClientBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IHttpClientFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/IHttpClientLogger.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IHttpMessageHandlerBuilderFilter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IHttpMessageHandlerFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/ISocketsHttpHandlerBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ITypedHttpClientFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Properties/InternalsVisibleTo.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/LifetimeTrackingHttpMessageHandler.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/LoggingHttpMessageHandler.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/LoggingHttpMessageHandlerBuilderFilter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Logging/LoggingScopeHttpMessageHandler.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/MetricsFactoryHttpMessageHandlerFilter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "ref/Microsoft.Extensions.Http.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/PACKAGE.md"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjection/SocketsHttpHandlerBuilderExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ValueStopwatch.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"