- id: "NuGet:Azure.Data:AppConfiguration"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Azure.Data:AppConfiguration:[1.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/Azure.Data.AppConfiguration.
    vcs:
      type: "Git"
      url: "https://github.com/Azure/azure-sdk-for-net.git"

- id: "NuGet:Azure.Data:AppConfiguration:[1.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/appconfiguration/Azure.Data.AppConfiguration/src"

- id: "NuGet:Azure.Data:AppConfiguration"
  curations:
    comment: |
      Map declared license based on
      https://github.com/Azure/azure-sdk-for-net/blob/Azure.Data.AppConfiguration_1.2.0/LICENSE.txt#L1-L21,
      https://github.com/Azure/azure-sdk-for-net/blob/Azure.Data.AppConfiguration_1.8.0/LICENSE.txt#L1-L21.
    declared_license_mapping:
      "https://www.nuget.org/packages/Azure.Data.AppConfiguration/1.2.0/license": "MIT"
      "https://www.nuget.org/packages/Azure.Data.AppConfiguration/1.8.0/license": "MIT"