- id: "NuGet:MDC.SignalSensitivity:Db"
  curations:
    comment: |
       Concluding the license based on project team input https://devstack.vwgroup.com/jira/browse/OSPO-3547?focusedId=28601586&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28601586
    concluded_license: "LicenseRef-CARIAD-Proprietary"
