- id: "NuGet:Microsoft.Extensions:Diagnostics:[10.0.0,)"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"
      path: "src/runtime/src/libraries/Microsoft.Extensions.Diagnostics/src"
    source_code_origins: [VCS]
- id: "NuGet:Microsoft.Extensions:Diagnostics"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/dotnet/blob/v10.0.0/LICENSE.TXT.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics/8.0.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics/8.0.1/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics/9.0.3/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics/10.0.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics/10.0.10/license": "MIT"
