- id: "NuGet:Microsoft.Extensions:Identity.Core"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.Extensions:Identity.Core:[10.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"

- id: "NuGet:Microsoft.Extensions:Identity.Core:[10.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/aspnetcore/src/Identity/Extensions.Core/src"

- id: "NuGet:Microsoft.Extensions:Identity.Core:[2.3.0,10.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/aspnetcore.git"

- id: "NuGet:Microsoft.Extensions:Identity.Core:[2.3.0,10.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Identity/Extensions.Core/src"

- id: "NuGet:Microsoft.Extensions:Identity.Core:(,2.3.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/aspnet/identity.git"

- id: "NuGet:Microsoft.Extensions:Identity.Core:(,2.3.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Core"
