- id: "NuGet:Microsoft.Extensions:Primitives"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.Extensions:Primitives:[10.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"

- id: "NuGet:Microsoft.Extensions:Primitives:[10.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/runtime/src/libraries/Microsoft.Extensions.Primitives/src"

- id: "NuGet:Microsoft.Extensions:Primitives:[5.0.0,10.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/runtime.git"

- id: "NuGet:Microsoft.Extensions:Primitives:[5.0.0,10.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/Microsoft.Extensions.Primitives/src"

- id: "NuGet:Microsoft.Extensions:Primitives:[2.2.0,5.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/extensions.git"

- id: "NuGet:Microsoft.Extensions:Primitives:[2.1.6,5.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Microsoft.Extensions.Primitives"

- id: "NuGet:Microsoft.Extensions:Primitives:(,2.1.6["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/aspnet/common.git"

- id: "NuGet:Microsoft.Extensions:Primitives:(,2.1.6["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Primitives/src"

- id: "NuGet:Microsoft.Extensions:Primitives:[5.0.0,)"
  curations:
    comment: |
      Mapping declared license based on
      https://github.com/dotnet/runtime/blob/v5.0.0/LICENSE.TXT,
      https://github.com/dotnet/runtime/blob/v8.0.0/LICENSE.TXT
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.Extensions.Primitives/8.0.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Extensions.Primitives/10.0.10/license": "MIT"
