- id: "NuGet:VWAC.DynamicExtensionService:Client:[1.0.0,)"
  curations:
    comment: |
      Package is proprietary closed-sourced software from a VW group organization.
    concluded_license: "VW-Group-Proprietary"
