- id: "NuGet:AWSSDK.AccessAnalyzer:PCL:[3.3.641,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AccessAnalyzer"
