---
id: "NuGet:Microsoft.Extensions:Hosting.Abstractions:8.0.0"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime.git"
  revision: "5535e31a712343a63f5d7d796cd874e563e5ac14"
path_excludes:
  - pattern: "src/native/external/brotli/common/dictionary.bin"
    reason: "OTHER"
  - pattern: "src/tests/**"
    reason: "TEST_OF"
  - pattern: "src/libraries/System.Reflection.Metadata/tests/**"
    reason: "TEST_OF"
  - pattern: "src/libraries/System.Net.Sockets/tests/**"
    reason: "TEST_OF"
  - pattern: "src/libraries/System.Runtime/tests/**"
    reason: "TEST_OF"
  - pattern: "src/libraries/System.Private.Xml.Linq/tests/**"
    reason: "TEST_OF"
  - pattern: "src/libraries/System.ServiceModel.Syndication/tests/**"
    reason: "TEST_OF"
  - pattern: "src/libraries/System.Text.RegularExpressions/tests/**"
    reason: "TEST_OF"
  - pattern: "src/native/external/libunwind/doc/**"
    reason: "DOCUMENTATION_OF"
  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
