- id: "NuGet:Azure.Security:KeyVault.Secrets"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Azure.Security:KeyVault.Secrets"
  curations:
    comment: |
      Map declared license based on
      https://github.com/Azure/azure-sdk-for-net/blob/Azure.Security.KeyVault.Secrets_4.6.0/LICENSE.txt.
      https://github.com/Azure/azure-sdk-for-net/blob/Azure.Security.KeyVault.Secrets_4.8.0/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/4.6.0/license": "MIT"
      "https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/4.8.0/license": "MIT"
      "https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/4.10.0/license": "MIT"

- id: "NuGet:Azure.Security:KeyVault.Secrets:[4.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/Azure/azure-sdk-for-net.git"

- id: "NuGet:Azure.Security:KeyVault.Secrets:[4.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/keyvault/Azure.Security.KeyVault.Secrets/src"

- id: "NuGet:Azure.Security:KeyVault.Secrets:4.8.0"
  curations:
    comment: |
      Package version format in metadata differs from repository version tag format.
    vcs:
      revision: "Azure.Security.KeyVault.Secrets_4.8.0"