---
id: "NuGet:Microsoft.Bcl:TimeProvider:(,8.0.1]"
path_excludes:
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmakein"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Sample*/**"
  reason: "TEST_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*fuzz*/**"
  reason: "TEST_OF"
- pattern: "**/*sample*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.clang-format"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.nuget/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/ChangeLog*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Dockerfile"
  reason: "BUILD_TOOL_OF"
- pattern: "**/FAQ"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Makefile*"
  reason: "BUILD_TOOL_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/System.Diagnostics.PerformanceCounter/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Tools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/cmake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/codecov.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure.ac"
  reason: "BUILD_TOOL_OF"
- pattern: "**/debug/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/generate*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/mock/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/package-lock.json"
  reason: "BUILD_TOOL_OF"
- pattern: "**/profiler/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
