- id: "NuGet:System.Configuration:ConfigurationManager"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:System.Configuration:ConfigurationManager"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/runtime/blob/v6.0.0/LICENSE.TXT#L1-L23
      https://github.com/dotnet/runtime/blob/v6.0.1/LICENSE.TXT
      https://github.com/dotnet/runtime/blob/v8.0.0/LICENSE.TXT#L1-L23
      https://github.com/dotnet/runtime/blob/v8.0.1/LICENSE.TXT#L1-L23
      https://github.com/dotnet/runtime/blob/v9.0.12/LICENSE.TXT
    declared_license_mapping:
      "https://www.nuget.org/packages/System.Configuration.ConfigurationManager/6.0.0/license": "MIT"
      "https://www.nuget.org/packages/System.Configuration.ConfigurationManager/6.0.1/license": "MIT"
      "https://www.nuget.org/packages/System.Configuration.ConfigurationManager/8.0.0/license": "MIT"
      "https://www.nuget.org/packages/System.Configuration.ConfigurationManager/8.0.1/license": "MIT"
      "https://www.nuget.org/packages/System.Configuration.ConfigurationManager/9.0.12/license": "MIT"

- id: "NuGet:System.Configuration:ConfigurationManager:[10.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/System.Configuration.ConfigurationManager
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"

- id: "NuGet:System.Configuration:ConfigurationManager:[10.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/runtime/src/libraries/System.Configuration.ConfigurationManager/src"

- id: "NuGet:System.Configuration:ConfigurationManager:[5.0.0,10.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/System.Configuration.ConfigurationManager
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/runtime.git"

- id: "NuGet:System.Configuration:ConfigurationManager:[5.0.0,10.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/System.Configuration.ConfigurationManager/src"



