- id: "NuGet:AWSSDK.AWSMarketplaceMetering:CoreCLR:[3.3.118,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AWSMarketplaceMetering"
