- id: "NuGet:AWSSDK.AWSMarketplaceMetering:PCL:[3.1.54,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AWSMarketplaceMetering"
