- id: "NuGet:Microsoft.VisualStudio:Mac.RazorAddin:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Razor/tooling/Microsoft.VisualStudio.Mac.RazorAddin"
