- id: "NuGet:Microsoft.Identity:Web.Certificateless"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.Identity:Web.Certificateless"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/Microsoft.Identity.Web.Certificateless.
    vcs:
      type: "Git"
      url: "https://github.com/AzureAD/microsoft-identity-web.git"

- id: "NuGet:Microsoft.Identity:Web.Certificateless"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Microsoft.Identity.Web.Certificateless"

- id: "NuGet:Microsoft.Identity:Web.Certificateless"
  curations:
    comment: |
      Map declared license based on
      https://github.com/AzureAD/microsoft-identity-web/blob/4.10.0/LICENSE#L1-L21,
      https://github.com/AzureAD/microsoft-identity-web/blob/4.11.0/LICENSE#L1-L21 and
      https://github.com/AzureAD/microsoft-identity-web/blob/4.12.2/LICENSE#L1-L21.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.Identity.Web.Certificateless/4.10.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Identity.Web.Certificateless/4.11.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Identity.Web.Certificateless/4.12.2/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.Identity.Web.Certificateless/4.13.2/license": "MIT"
