- id: "NuGet:AWSSDK.CodeGuruProfiler:PCL:[3.3.642,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/CodeGuruProfiler"
