- id: "NuGet:Azure.Analytics:Purview.Scanning"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/purview/Azure.Analytics.Purview.Scanning"
