- id: "NuGet:AWSSDK.PinpointSMSVoice:PCL:[3.3.409,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/PinpointSMSVoice"
