- id: "NuGet:Azure.Messaging:ServiceBus"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Azure.Messaging:ServiceBus"
  curations:
    comment: |
      Map declared license based on
      https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.20.2/sdk/servicebus/Azure.Messaging.ServiceBus/src/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.20.2/license": "MIT"

- id: "NuGet:Azure.Messaging:ServiceBus:[7.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/Azure.Messaging.ServiceBus.
    vcs:
      type: "Git"
      url: "https://github.com/Azure/azure-sdk-for-net.git"

- id: "NuGet:Azure.Messaging:ServiceBus:[7.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/servicebus/Azure.Messaging.ServiceBus/src"
