---
id: "NuGet:Microsoft.Extensions:Configuration.Abstractions:8.0.0"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime"
  revision: "5535e31a712343a63f5d7d796cd874e563e5ac14"
license_finding_curations:
- path: "src/ConfigurationDebugViewContext.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ConfigurationExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ConfigurationKeyNameAttribute.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ConfigurationPath.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ConfigurationRootExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfiguration.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfigurationBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfigurationManager.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfigurationProvider.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfigurationRoot.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfigurationSection.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/IConfigurationSource.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "ref/Microsoft.Extensions.Configuration.Abstractions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/PACKAGE.md"
  start_lines: "82"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"