- id: "NuGet:System.Threading:RateLimiting"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:System.Threading:RateLimiting"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/corefx.git"

- id: "NuGet:System.Threading:RateLimiting"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/System.Threading.RateLimiting/src"
