- id: "NuGet:AWSSDK.KinesisVideoArchivedMedia:CoreCLR:[3.3.199,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/KinesisVideoArchivedMedia"
