---
id: "NuGet:Microsoft.Extensions:DependencyInjection:8.0.1"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime"
  revision: "81cabf2857a01351e5ab578947c7403a5b128ad1"
path_excludes:
- pattern: "tests/**"
  reason: "TEST_OF"
license_finding_curations:
- path: "src/ServiceLookup/CallSiteChain.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CallSiteFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/CallSiteJsonFormatter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CallSiteKind.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CallSiteResultCacheLocation.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CallSiteRuntimeResolver.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CallSiteValidator.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CallSiteVisitor.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/CompiledServiceProviderEngine.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ConstantCallSite.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ConstructorCallSite.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DefaultServiceProviderFactory.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/DependencyInjectionEventSource.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/DynamicServiceProviderEngine.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/Expressions/ExpressionResolverBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/Expressions/ExpressionsServiceProviderEngine.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/FactoryCallSite.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/IEnumerableCallSite.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ILEmit/ILEmitResolverBuilderContext.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ILEmit/ILEmitServiceProviderEngine.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Properties/InternalsVisibleTo.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "ref/Microsoft.Extensions.DependencyInjection.Forwards.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "ref/Microsoft.Extensions.DependencyInjection.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/PACKAGE.md"
  start_lines: "50"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ResultCache.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/RuntimeServiceProviderEngine.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceCacheKey.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceCallSite.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceCollectionContainerBuilderExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceDescriptorExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceIdentifier.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceLookupHelpers.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceProvider.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceProviderCallSite.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceProviderEngine.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ServiceProviderEngineScope.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceProviderOptions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/StackGuard.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ServiceLookup/ThrowHelper.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Properties/TypeForwards.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"