- id: "NuGet:Azure.MixedReality:RemoteRendering"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/remoterendering/Azure.MixedReality.RemoteRendering"
