- id: "NuGet:VWAC.DataPlatform:Streaming.Client:[3.0.0,)"
  curations:
    comment: |
      Package is proprietary closed-sourced software from a VW group organization.
    concluded_license: "VW-Group-Proprietary"
