- id: "NuGet:AWSSDK.ConnectParticipant:PCL:[3.3.636,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ConnectParticipant"
