- id: "NuGet:Microsoft.ApplicationInsights:PerfCounterCollector"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.ApplicationInsights:PerfCounterCollector:[2.12.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/Microsoft/ApplicationInsights-dotnet.git"

- id: "NuGet:Microsoft.ApplicationInsights:PerfCounterCollector:[2.12.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "WEB/Src/PerformanceCollector/PerformanceCollector"

- id: "NuGet:Microsoft.ApplicationInsights:PerfCounterCollector"
  curations:
    comment: |
      Map declared license based on
      https://github.com/microsoft/ApplicationInsights-dotnet/blob/2.23.0/LICENSE.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.ApplicationInsights.PerfCounterCollector/2.23.0/license": "MIT"