---
id: "Conan::eigen:3.3.9-4"
path_excludes:
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*bench*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/INSTALL"
  reason: "DOCUMENTATION_OF"
- pattern: "**/cmake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/debug/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/demos/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
