- id: "NuGet:Microsoft.Azure:ApplicationInsights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query"
