- id: "NuGet:Microsoft.Azure:CognitiveServices.ContentModerator"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/cognitiveservices/Vision.ContentModerator"
