- id: "NuGet:Microsoft.Azure:ContainerRegistry"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/containerregistry/Microsoft.Azure.ContainerRegistry"
