- id: "NuGet:Microsoft.Azure:EventHubs.Perf"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/eventhub/Microsoft.Azure.EventHubs/perf"
