- id:  "NuGet:Microsoft.Azure:Functions.Worker.Extensions.Http.AspNetCore:2.0.1"
  curations:
    comment: |
      Map declared license based on
      https://github.com/Azure/azure-functions-dotnet-worker/blob/http-aspnetcore-extension-2.0.1/LICENSE.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore/2.0.1/license": "MIT"
