- id: "NuGet:Microsoft.Azure:Functions.Worker.Grpc:2.51.0"
  curations:
    comment: |
      Map declared license based on
      https://github.com/Azure/azure-functions-dotnet-worker/blob/2.51.0/LICENSE.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Grpc/2.51.0/license": "MIT"
