- id: "NuGet:Microsoft.Azure:Graph.RBAC"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/graphrbac/Microsoft.Azure.Graph.RBAC"
