- id: "NuGet:Microsoft.Azure:Management.ChangeAnalysis"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/changeanalysis/Microsoft.Azure.Management.ChangeAnalysis"
