- id: "NuGet:Microsoft.Azure:Management.AlertsManagement"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/alertsmanagement/Microsoft.Azure.Management.AlertsManagement"
