- id: "NuGet:Microsoft.Azure:Management.DataLake.Store"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datalake-store/Microsoft.Azure.Management.DataLake.Store"
