- id: "NuGet:Microsoft.Azure:Management.Billing"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/billing/Microsoft.Azure.Management.Billing"
