- id: "NuGet:Microsoft.Azure:Management.PrivateDns"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/privatedns/Microsoft.Azure.Management.PrivateDns"
