- id: "NuGet:Microsoft.Azure:Management.Automanage"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/automanage/Microsoft.Azure.Management.Automanage"
