- id: "NuGet:Microsoft.Azure:Management.Insights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/insights/Microsoft.Azure.Management.Insights"
