- id: "NuGet:Microsoft.Azure:Management.MachineLearningServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/machinelearningservices/Microsoft.Azure.Management.MachineLearningServices"
