- id: "NuGet:Microsoft.Azure:Management.ManagedServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/managedservices/Microsoft.Azure.Management.ManagedServices"
