- id: "NuGet:Microsoft.Azure:Management.Kusto"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/kusto/Microsoft.Azure.Management.Kusto"
