- id: "NuGet:Microsoft.Azure:Management.Batch"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/batch/Microsoft.Azure.Management.Batch"
