- id: "NuGet:Microsoft.Azure:Management.Attestation"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/attestation/Microsoft.Azure.Management.Attestation"
