- id: "NuGet:Microsoft.Azure:Management.HDInsight"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/hdinsight/Microsoft.Azure.Management.HDInsight"
