- id: "NuGet:Microsoft.Azure:Management.CognitiveServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/cognitiveservices/Microsoft.Azure.Management.CognitiveServices"
