- id: "NuGet:Microsoft.Azure:Management.NotificationHubs"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/notificationhubs/Microsoft.Azure.Management.NotificationHubs"
