- id: "NuGet:Microsoft.Azure:Management.EdgeGateway"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/edgegateway/Microsoft.Azure.Management.EdgeGateway"
