- id: "NuGet:Microsoft.Azure:Management.Advisor"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/advisor/Microsoft.Azure.Management.Advisor"
