- id: "NuGet:Microsoft.Azure:Management.Logz"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/logz/Microsoft.Azure.Management.Logz"
