- id: "NuGet:Microsoft.Azure:Management.Reservations"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/reservations/Microsoft.Azure.Management.Reservations"
