- id: "NuGet:Microsoft.Azure:Management.NetApp"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/netapp/Microsoft.Azure.Management.NetApp"
