- id: "NuGet:Microsoft.Azure:Management.Peering"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/peering/Microsoft.Azure.Management.Peering"
