- id: "NuGet:Microsoft.Azure:Management.Maps"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/maps/Microsoft.Azure.Management.Maps"
