- id: "NuGet:Microsoft.Azure:Management.DataFactory"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datafactory/Microsoft.Azure.Management.DataFactory"
