- id: "NuGet:Microsoft.Azure:Management.IotCentral"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/iotcentral/Microsoft.Azure.Management.IotCentral"
