- id: "NuGet:Microsoft.Azure:Management.Migrate.ResourceMover"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/resourcemover/Microsoft.Azure.Management.Migrate"
