- id: "NuGet:Microsoft.Azure:Management.Quota"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/quota/Microsoft.Azure.Management.Quota"
