- id: "NuGet:Microsoft.Azure:Management.LabServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/labservices/Microsoft.Azure.Management.LabServices"
