- id: "NuGet:Microsoft.Azure:Management.DevSpaces"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/devspaces/Microsoft.Azure.Management.DevSpaces"
