- id: "NuGet:Microsoft.Azure:Management.ManagedNetwork"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/managednetwork/Microsoft.Azure.Management.ManagedNetwork"
