- id: "NuGet:Microsoft.Azure:Management.LocationBasedServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/locationbasedservices/Microsoft.Azure.Management.LocationBasedServices"
