- id: "NuGet:Microsoft.Azure:Management.Elastic"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/elastic/Microsoft.Azure.Management.Elastic"
