- id: "NuGet:Microsoft.Azure:Management.DeviceProvisioningServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/deviceprovisioningservices/Microsoft.Azure.Management.DeviceProvisioningServices"
