- id: "NuGet:Microsoft.Azure:Management.Monitor"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/monitor/Microsoft.Azure.Management.Monitor"
