- id: "NuGet:Microsoft.Azure:Management.Authorization"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/authorization/Microsoft.Azure.Management.Authorization"
