- id: "NuGet:Microsoft.Azure:Management.DataBox"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/databox/Microsoft.Azure.Management.DataBox"
