- id: "NuGet:Microsoft.Azure:Management.HybridDataManager"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/hybriddatamanager/Microsoft.Azure.Management.HybridDataManager"
