- id: "NuGet:Microsoft.Azure:Management.Network"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/network/Microsoft.Azure.Management.Network"
