- id: "NuGet:Microsoft.Azure:Management.EventGrid"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/eventgrid/Microsoft.Azure.Management.EventGrid"
