- id: "NuGet:Microsoft.Azure:Management.DataShare"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datashare/Microsoft.Azure.Management.DataShare"
