- id: "NuGet:Microsoft.Azure:Management.PolicyInsights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/policyinsights/Microsoft.Azure.Management.PolicyInsights"
