- id: "NuGet:Microsoft.Azure:Management.Avs"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/avs/Microsoft.Azure.Management.Avs"
