- id: "NuGet:Microsoft.Azure:Management.ManagedServiceIdentity"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/managedserviceidentity/Microsoft.Azure.Management.ManagedServiceIdentity"
