- id: "NuGet:Microsoft.Azure:Management.DataLake.Analytics"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datalake-analytics/Microsoft.Azure.Management.DataLake.Analytics"
