- id: "NuGet:Microsoft.Azure:Management.DataMigration"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datamigration/Microsoft.Azure.Management.DataMigration"
