- id: "NuGet:Microsoft.Azure:Management.ExtendedLocation"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/extendedlocation/Microsoft.Azure.Management.ExtendedLocation"
