- id: "NuGet:Microsoft.Azure:Management.MixedReality"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/mixedreality/Microsoft.Azure.Management.MixedReality"
