- id: "NuGet:Microsoft.Azure:Management.CosmosDB"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB"
