- id: "NuGet:Microsoft.Azure:Management.DataBoxEdge"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/databoxedge/Microsoft.Azure.Management.DataBoxEdge"
