- id: "NuGet:Microsoft.Azure:Management.DataProtection"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/dataprotection/Microsoft.Azure.Management.DataProtection"
