- id: "NuGet:Microsoft.Azure:Management.IotHub"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/iothub/Microsoft.Azure.Management.IotHub"
