- id: "NuGet:Microsoft.Azure:Management.HybridCompute"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/hybridcompute/Microsoft.Azure.Management.HybridCompute"
