- id: "NuGet:Microsoft.Azure:Management.Blueprint"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/blueprint/Microsoft.Azure.Management.Blueprint"
