- id: "NuGet:Microsoft.Azure:Management.CustomProviders"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/customproviders/Microsoft.Azure.Management.CustomProviders"
