- id: "NuGet:Microsoft.Azure:Management.MachineLearningCompute"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/machinelearningcompute/Microsoft.Azure.Management.MachineLearningCompute"
