- id: "NuGet:Microsoft.Azure:OperationalInsights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/operationalinsights/Microsoft.Azure.OperationalInsights"
