- id: "NuGet:Microsoft.Azure:WebJobs.Extensions.EventHubs"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs"
