- id: "NuGet:Microsoft.Azure:WebJobs.Extensions.EventGrid"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/eventgrid/Microsoft.Azure.WebJobs.Extensions.EventGrid"
