- id: "NuGet:Microsoft.AspNet:Identity.AspNetCoreCompat:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Identity/src/AspNetCoreCompat"
