- id: "NuGet:System.Reflection:Primitives"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:System.Reflection:Primitives"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/corefx.git"

- id: "NuGet:System.Reflection:Primitives"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/System.Reflection.Primitives/src"

- id: "NuGet:System.Reflection:Primitives:4.3.0"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/System.Reflection.Primitives/4.3.0.
    vcs:
      revision: "8808e3e7f9749a168f86180496d6ea0f8e159db2"
