---
id: "NuGet:Azure.Extensions:AspNetCore.Configuration.Secrets:[1.0.0,)"
source_code_origin: VCS
path_excludes:
- pattern: "sdk/core/Azure.Core/tests/common/TestData/ResourceProviderData/ResourceProviderData-Collapsed.json"
  reason: "OTHER"
  comment: "Excluded sdk/core/Azure.Core/tests/common/TestData/ResourceProviderData/ResourceProviderData-Collapsed.json due to a timeout error"
- pattern: "sdk/core/System.ClientModel/tests/client/TestData/ResourceProviderData/ResourceProviderData-Collapsed.json"
  reason: "OTHER"
  comment: "Excluded sdk/core/System.ClientModel/tests/client/TestData/ResourceProviderData/ResourceProviderData-Collapsed.json due to a timeout error"
- pattern: "sdk/cognitiveservices/Search.BingEntitySearch/tests/**"
  reason: "TEST_OF"
  comment: "Exclude the Tests folder, as it contains test data"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
  comment: "CONTRIBUTING.md is excluded from assessment here because the file is not applicable in the present case as the package is not considered in contribution context"
- pattern: "CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
  comment: "CONTRIBUTING.md is excluded from assessment here because the file is not applicable in the present case as the package is not considered in contribution context"
- pattern: "doc/**"
  reason: "DOCUMENTATION_OF"
  comment: "Exclude the doc folder, as it contains doc files"
- pattern: "samples/**"
  reason: "DOCUMENTATION_OF"
  comment: "Exclude the samples folder, as it contains samples files"
- pattern: "tools/**"
  reason: "BUILD_TOOL_OF"
  comment: "Exclude the tools folder, as it contains tool files"
- pattern: "sdk/schemaregistry/Azure.Data.SchemaRegistry/samples/**"
  reason: "DOCUMENTATION_OF"
  comment: "Exclude the samples folder, as it contains samples files"