- id: "NuGet::GraphQL-Parser"
  curations:
    comment: |
      Map declared license based on
      https://github.com/graphql-dotnet/parser/blob/9.5.1/LICENSE.md.
    declared_license_mapping:
      "https://www.nuget.org/packages/GraphQL-Parser/9.5.1/license": "MIT"
