---
id: "NuGet:Microsoft.ApplicationInsights:WorkerService:2.22.0"
vcs:
  type: "Git"
  url: "https://github.com/Microsoft/ApplicationInsights-dotnet.git"
  revision: "43825e06a22cdfb702fc199a7ba99a7d541d48c6"
license_finding_curations:
- path: "LICENSE"
  start_lines: "1"
  line_count: 21
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "BASE/LICENSE"
  start_lines: "1"
  line_count: 21
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "LOGGING/LICENSE"
  start_lines: "1"
  line_count: 21
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "WEB/LICENSE"
  start_lines: "1"
  line_count: 21
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "NETCORE/LICENSE"
  start_lines: "1"
  line_count: 21
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: ".scripts/release_NupkgAudit.ps1"
  start_lines: "31"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: ".scripts/release_NupkgAudit.ps1"
  start_lines: "31"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "LOGGING/ThirdPartyNotices.txt"
  start_lines: "4"
  line_count: 285
  detected_license: "NOASSERTION AND Apache-2.0 AND MIT AND BSD-3-Clause"
  concluded_license: "Apache-2.0 AND MIT AND BSD-3-Clause"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "NETCORE/ThirdPartyNotices.txt"
  start_lines: "5"
  line_count: 213
  detected_license: "NOASSERTION AND Apache-2.0"
  concluded_license: "Apache-2.0"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"