---
id: "NuGet:Microsoft.Extensions:DependencyModel:(,3.1.6]"
path_excludes:
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.nuspec"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/azure-pipelines.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build.proj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/changelog*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/performance/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
