- id: "NuGet:AWSSDK.AutoScalingPlans:PCL:[3.3.222,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AutoScalingPlans"
