---
id: "NuGet:Microsoft.Data:Sqlite.Core:(,7.0.20]"
path_excludes:
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.nuspec"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*bench*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/azure-pipelines.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/generate*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
