- id: "NuGet:AWSSDK.Route53Resolver:CoreCLR:[3.3.409,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/Route53Resolver"
