- id: "NuGet:AutoMapper.Extensions:Microsoft.DependencyInjection"
  curations:
    comment: |
      Map declared license based on
      https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/v8.1.1/LICENSE.
    declared_license_mapping:
      "https://www.nuget.org/packages/AutoMapper.Extensions.Microsoft.DependencyInjection/8.1.1/license": "MIT"
      "https://www.nuget.org/packages/AutoMapper.Extensions.Microsoft.DependencyInjection/12.0.1/license": "MIT"
