- id: "NuGet:AWSSDK.ElasticInference:PCL:[3.3.639,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ElasticInference"
