- id: "NuGet:Azure.Monitor:OpenTelemetry.Exporter"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter"
