- id: "NuGet:Microsoft.AspNetCore:Analyzers.FeatureDetection.Sources:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Analyzers/shared/FeatureDetection"
