- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer"
  curations:
    comment: |
      Enforce scanning the code repository because there are issues using the source artifact via internal package registries (e.g., Artifactory).
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/aspnetcore/blob/v7.0.20/src/Security/Authentication/JwtBearer/src/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/7.0.20/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/10.0.0/license": "MIT"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:[10.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:[10.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/aspnetcore/src/Security/Authentication/JwtBearer/src"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:[2.3.0,10.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/aspnetcore.git"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:[2.3.0,10.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Security/Authentication/JwtBearer/src"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:2.3.9"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/2.3.9 and
      https://github.com/dotnet/aspnetcore/tree/dbf71c0b22dc0ad6d7f6570c531e5c70d676c1b7.
    vcs:
      revision: "dbf71c0b22dc0ad6d7f6570c531e5c70d676c1b7"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:2.3.8"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/2.3.8 and
      https://github.com/dotnet/aspnetcore/tree/afaf0bba8a9fc86e8aa551e8dd498c96461f09c5.
    vcs:
      revision: "afaf0bba8a9fc86e8aa551e8dd498c96461f09c5"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:2.3.0"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/2.3.0 and
      https://github.com/dotnet/aspnetcore/tree/ad30aa9595095b855c8787236996876f9f757191.
    vcs:
      revision: "ad30aa9595095b855c8787236996876f9f757191"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:[2.0.0,2.2.0]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/aspnet/Security.git"

- id: "NuGet:Microsoft.AspNetCore:Authentication.JwtBearer:[2.0.0,2.2.0]"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Microsoft.AspNetCore.Authentication.JwtBearer"
