- id: "NuGet:Microsoft.AspNetCore:Components.WebAssembly.Templates:[3.1.6,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates"
