- id: "NuGet:Microsoft.AspNetCore:Components.WebAssembly.Build:[3.1.6,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Components/WebAssembly/Build/src"
