- id: "NuGet:Microsoft.AspNetCore:ConcurrencyLimiter.Microbenchmarks:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Middleware/ConcurrencyLimiter/perf/Microbenchmarks"
