- id: "NuGet:Microsoft.AspNetCore:Connections.Abstractions:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Servers/Connections.Abstractions/src"
