- id: "NuGet:Microsoft.AspNetCore:DataProtection.StackExchangeRedis:[2.2.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/DataProtection/StackExchangeRedis/src"
