- id: "NuGet:Microsoft.AspNetCore:DataProtection:[2.0.0,2.1.1]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
      Found VCS via package registry, see https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection
    vcs:
      type: "Git"
      url: "https://github.com/aspnet/DataProtection.git"
      path: "src/Microsoft.AspNetCore.DataProtection"
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.AspNetCore:DataProtection"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/dotnet/blob/v10.0.7/src/aspnetcore/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/10.0.7/license": "MIT"

- id: "NuGet:Microsoft.AspNetCore:DataProtection:[2.2.0,9.0.15]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
      Found VCS via package registry, see https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/aspnetcore.git"
      path: "src/DataProtection/DataProtection/src"
    source_code_origins: [VCS]
- id: "NuGet:Microsoft.AspNetCore:DataProtection:[10.0.0,10.0.7]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
      Found VCS via package registry, see https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"
      path: "src/aspnetcore/src/DataProtection/DataProtection/src"
    source_code_origins: [VCS]
