- id: "NuGet:Microsoft.AspNetCore:HeaderPropagation:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Middleware/HeaderPropagation/src"
