- id: "NuGet:Microsoft.AspNetCore:Http.Abstractions.Microbenchmarks:[6.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Http/Http.Abstractions/perf/Microbenchmarks"
