- id: "NuGet:Microsoft.AspNetCore:Localization.Routing:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Middleware/Localization.Routing/src"
