- id: "NuGet:Microsoft.AspNetCore:Mvc.Razor.Extensions.Version2_X:[5.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Razor/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/src"
