- id: "NuGet:Microsoft.AspNetCore:Mvc.Razor.RuntimeCompilation:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Mvc/Mvc.Razor.RuntimeCompilation/src"
