- id: "NuGet:Microsoft.AspNetCore:Mvc.Performance.Views:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Mvc/benchmarks/Microsoft.AspNetCore.Mvc.Performance.Views"
