- id: "NuGet:Microsoft.AspNetCore:Mvc.NewtonsoftJson"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.AspNetCore:Mvc.NewtonsoftJson:[10.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"

- id: "NuGet:Microsoft.AspNetCore:Mvc.NewtonsoftJson:[10.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/aspnetcore/src/Mvc/Mvc.NewtonsoftJson/src"

- id: "NuGet:Microsoft.AspNetCore:Mvc.NewtonsoftJson:[3.0.0,10.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/aspnetcore.git"

- id: "NuGet:Microsoft.AspNetCore:Mvc.NewtonsoftJson:[3.0.0,10.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Mvc/Mvc.NewtonsoftJson/src"

- id: "NuGet:Microsoft.AspNetCore:Mvc.NewtonsoftJson:[10.0.0,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/dotnet/blob/v10.0.0/LICENSE.TXT#L1-L23
      https://github.com/dotnet/dotnet/blob/v10.0.9/LICENSE.TXT#L1-L23
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/10.0.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/10.0.9/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/10.0.10/license": "MIT"
