- id: "NuGet:Microsoft.AspNetCore:Mvc.Testing.Tasks:[6.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Mvc/Mvc.Testing.Tasks/src"
