- id: "NuGet:Microsoft.AspNetCore:Mvc.Performance:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Mvc/benchmarks/Microsoft.AspNetCore.Mvc.Performance"
