- id: "NuGet:Microsoft.AspNetCore:Routing.Performance:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Http/Routing/perf"
