- id: "NuGet:Microsoft.AspNetCore:Routing:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Http/Routing/src"

- id: "NuGet:Microsoft.AspNetCore:Routing:(,3.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Microsoft.AspNetCore.Routing"
