- id: "NuGet:Microsoft.AspNetCore:Server.IntegrationTesting:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Hosting/Server.IntegrationTesting/src"
