- id: "NuGet:Microsoft.AspNetCore:Server.Kestrel.Core:[2.1.7,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Servers/Kestrel/Core/src"
