- id: "NuGet:Microsoft.AspNetCore:SignalR.Protocols.NewtonsoftJson:[3.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/SignalR/common/Protocols.NewtonsoftJson/src"
