- id: "NuGet:Microsoft.AspNetCore:StaticFiles:2.1.7"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/StaticFiles/src/Microsoft.AspNetCore.StaticFiles"
- id: "NuGet:Microsoft.AspNetCore:StaticFiles:[2.1.8,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Middleware/StaticFiles/src"
