- id: "NuGet:Microsoft.AspNetCore:WebUtilities.Microbenchmarks:[6.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Http/WebUtilities/perf/Microbenchmarks"
