- id: "NuGet:AWSSDK:AlexaForBusiness:[3.3.201,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AlexaForBusiness"
