- id: "NuGet:AWSSDK:AmplifyUIBuilder:[3.7.174,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AmplifyUIBuilder"
