- id: "NuGet:AWSSDK:ApplicationCostProfiler:[3.7.35,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ApplicationCostProfiler"
