- id: "NuGet:AWSSDK:AWSMarketplaceCommerceAnalytics:[3.1.18,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/AWSMarketplaceCommerceAnalytics"
