- id: "NuGet:AWSSDK:BillingConductor:[3.7.231,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/BillingConductor"
