- id: "NuGet:AWSSDK:ChimeSDKIdentity:[3.7.91,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ChimeSDKIdentity"
