- id: "NuGet:AWSSDK:ChimeSDKMediaPipelines:[3.7.261,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ChimeSDKMediaPipelines"
