- id: "NuGet:AWSSDK:CodeStarNotifications:[3.3.623,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/CodeStarNotifications"
