- id: "NuGet:AWSSDK:CustomerProfiles:[3.5.65,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/CustomerProfiles"
