- id: "NuGet:AWSSDK:ElasticLoadBalancingV2:[3.1.92,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ElasticLoadBalancingV2"
