- id: "NuGet:AWSSDK:IoTSecureTunneling:[3.3.638,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/IoTSecureTunneling"
