- id: "NuGet:AWSSDK:KinesisAnalytics:[3.1.92,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/KinesisAnalytics"
