- id: "NuGet:AWSSDK:ManagedBlockchain:[3.3.502,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ManagedBlockchain"
