- id: "NuGet:AWSSDK:PersonalizeRuntime:[3.3.528,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/PersonalizeRuntime"
