- id: "NuGet:AWSSDK:ServerMigrationService:[3.3.14,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ServerMigrationService"
