- id: "NuGet:AWSSDK:ServiceDiscovery:[3.3.203,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ServiceDiscovery"
