- id: "NuGet:AWSSDK:TranscribeService:[3.3.224,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/TranscribeService"
