---
id: "Conan::zlib222:(,1.3.2]"
path_excludes:
- pattern: "**/*.bazel"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmakein"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.pdf"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*example*/**"
  reason: "EXAMPLE_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/ChangeLog*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/FAQ"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Makefile*"
  reason: "BUILD_TOOL_OF"
- pattern: "**/cmake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure.ac"
  reason: "BUILD_TOOL_OF"
license_finding_curations:
- path: "**/contrib/iostream3/README"
  start_lines: "26"
  line_count: 2
  detected_license: "NOASSERTION"
  concluded_license: "0BSD"
  reason: "DOCUMENTATION_OF"
  comment: |
    Match on https://github.com/madler/zlib/blob/v1.3.1/contrib/iostream3/README#L26-L27
    NOASSERTION is detected because of below content in file:
    https://github.com/madler/zlib/blob/v1.3.1/contrib/iostream3/README#L26-L27
- path: "**/*.c"
  detected_license: "Zlib AND NOASSERTION"
  concluded_license: "Zlib"
  reason: "REFERENCE"
  comment: |
    Match on https://github.com/madler/zlib/blob/v1.3.1/inffast.c#L3
    Reference link- https://github.com/madler/zlib/blob/v1.3.1/zlib.h#L6-L20
    NOASSERTION is detected because of below content in file:
    For conditions of distribution and use, see copyright notice in zlib.h
