---
id: "Conan::protobuf:(,31.0]"
path_excludes:
- pattern: "**/*-demo*"
  reason: "EXAMPLE_OF"
- pattern: "**/*.bazel"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.gemspec"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.m4"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.nuspec"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.podspec"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.rake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*bench*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*example*/**"
  reason: "EXAMPLE_OF"
- pattern: "**/*fuzz*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.bazelrc"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.clang-format"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/BUILD"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CHANGES.txt"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CODE_OF_CONDUCT.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/DevTools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Dockerfile"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Google.Protobuf.Conformance/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Makefile*"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Rakefile*"
  reason: "BUILD_TOOL_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/build*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build.bat"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build.rs"
  reason: "BUILD_TOOL_OF"
- pattern: "**/ci/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/cmake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure.ac"
  reason: "BUILD_TOOL_OF"
- pattern: "**/conformance/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/generate*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/m4/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/setup.cfg"
  reason: "BUILD_TOOL_OF"
- pattern: "**/setup.py"
  reason: "BUILD_TOOL_OF"
- pattern: "**/third_party/utf8_range/utf8_corpus_dir/utf8_corpus_kuhn.txt"
  reason: "TEST_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
license_finding_curations:
- path: "**/pom.xml"
  start_lines: "20"
  line_count: 7
  detected_license: "BSD-3-Clause-No-Nuclear-Warranty AND BSD-3-Clause"
  concluded_license: "BSD-3-Clause"
  reason: "INCORRECT"
  comment: |
    Match on BSD-3-Clause at the URL: 'https://github.com/protocolbuffers/protobuf/blob/v31.0/ruby/pom.xml#L22'
    and at the URL: 'https://github.com/protocolbuffers/protobuf/blob/v31.0/java/protoc/pom.xml#L22'.
    No reference of the BSD-3-Clause-No-Nuclear-Warranty License at detected path and line numbers.
