---
id: "Conan::abseil:(,20250512.0]"
path_excludes:
- pattern: "**/*.bazel"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.clang-format"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/ci/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/conanfile.py"
  reason: "BUILD_TOOL_OF"
