---
id: "NuGet:Microsoft.Bcl:Cryptography:(,10.0.2]"
path_excludes:
- pattern: "**/*.bazel"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmake"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.cmakein"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.gradle"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.nuspec"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*Example*/**"
  reason: "EXAMPLE_OF"
- pattern: "**/*Fuzz*/**"
  reason: "TEST_OF"
- pattern: "**/*Sample*/**"
  reason: "TEST_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*bench*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*example*/**"
  reason: "EXAMPLE_OF"
- pattern: "**/*fuzz*/**"
  reason: "TEST_OF"
- pattern: "**/*sample*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.appveyor.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.bazelrc"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.circleci/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.clang-format"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.nuget/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/AssemblyFixtureSupport/**"
  reason: "TEST_OF"
- pattern: "**/BUILD"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Build/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CHANGELOG*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CI/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CODE_OF_CONDUCT.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/ChangeLog*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CompleteStatement/**"
  reason: "TEST_OF"
- pattern: "**/DevTools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Dockerfile"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Makefile*"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Performance/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/PerformanceCollector/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/PerformanceSensitiveAnalyzers/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Profiler/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/System.Diagnostics.PerformanceCounter/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Tools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/Wasm.Performance/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/azure-pipelines.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build.bat"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build.proj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/cmake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/codecov.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure"
  reason: "BUILD_TOOL_OF"
- pattern: "**/configure.ac"
  reason: "BUILD_TOOL_OF"
- pattern: "**/debug/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/generate*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/gradlew.bat"
  reason: "BUILD_TOOL_OF"
- pattern: "**/package-lock.json"
  reason: "BUILD_TOOL_OF"
- pattern: "**/perf/**"
  reason: "TEST_OF"
- pattern: "**/performance/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/profiler/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/setup.cfg"
  reason: "BUILD_TOOL_OF"
- pattern: "**/setup.py"
  reason: "BUILD_TOOL_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
