---
id: "NuGet:Microsoft.AspNetCore:Mvc.WebApiCompatShim:2.3.0"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/aspnetcore.git"
  revision: "ad30aa9595095b855c8787236996876f9f757191"
path_excludes:
- pattern: "src/Http/Http.Extensions/test/**"
  reason: "TEST_OF"
- pattern: "src/Security/Authentication/test/**"
  reason: "TEST_OF"
- pattern: "src/SignalR/clients/cpp/test/**"
  reason: "TEST_OF"
- pattern: "src/Middleware/WebSockets/test/**"
  reason: "TEST_OF"
- pattern: "src/AzureIntegration/test/**"
  reason: "TEST_OF"
- pattern: "src/Identity/testassets/**"
  reason: "TEST_OF"
- pattern: "src/SignalR/clients/cpp/.nuget/NuGet.exe"
  reason: "BUILD_TOOL_OF"
- pattern: "src/AzureIntegration/test/Microsoft.AspNetCore.AzureAppServices.FunctionalTests/Assets/AspNetCore1xMvc/wwwroot/lib/jquery-validation-unobtrusive/.bower.json"
  reason: "TEST_OF"
- pattern: "src/Identity/testassets/Identity.DefaultUI.WebSite/wwwroot/lib/jquery-validation-unobtrusive/.bower.json"
  reason: "TEST_OF"
- pattern: "src/Installers/Windows/files/eula.rtf"
  reason: "BUILD_TOOL_OF"
license_finding_curations:
- path: "src/SignalR/clients/cpp/NuGet/signalrclientcpp.nuspec.template"
  start_lines: "9"
  line_count: 1
  detected_license: "LicenseRef-scancode-ms-net-library"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Hosting/Server.IntegrationTesting/src/Deployers/RemoteWindowsDeployer/RemoteWindowsDeploymentParameters.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "Apache-2.0"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/Identity/UI/src/Microsoft.AspNetCore.Identity.UI.csproj"
  start_lines: "16"
  line_count: 4
  detected_license: "NOASSERTION"
  concluded_license: "Apache-2.0 AND MIT"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/Installers/Windows/AspNetCoreModule-Setup/IIS-Setup/IIS-Common/README.md"
  start_lines: "6"
  line_count: 9
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/AspNetCoreModule-Setup/IIS-Setup/README.md"
  start_lines: "6"
  line_count: 9
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/SharedFrameworkBundle/Bundle.wxs"
  start_lines: "5"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/SharedFrameworkBundle/thm.wxl"
  start_lines: "21"
  line_count: 2
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/SharedFrameworkBundle/thm.xml"
  start_lines: "21"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/WindowsHostingBundle/Bundle.wxs"
  start_lines: "7"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/WindowsHostingBundle/thm.wxl"
  start_lines: "21"
  line_count: 2
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Installers/Windows/WindowsHostingBundle/thm.xml"
  start_lines: "23"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/Mvc/Settings.StyleCop"
  start_lines: "322"
  line_count: 124
  detected_license: "NOASSERTION AND Apache-2.0"
  concluded_license: "Apache-2.0"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/Security/Authentication/Cookies/src/ITicketStore.cs"
  start_lines: "1"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "Apache-2.0"
  reason: "REFERENCE"
  comment: "True Positive"