- id: "NuGet:Microsoft.Win32:SystemEvents:[5.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/Microsoft.Win32.SystemEvents"

- id: "NuGet:Microsoft.Win32:SystemEvents:[6.0.0,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/runtime/blob/v6.0.0/LICENSE.TXT#L1-L23.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.Win32.SystemEvents/6.0.0/license": "MIT"
