ort:
  addAuthorsToCopyrights: false
  allowedProcessEnvironmentVariableNames:
  - "PASSPORT"
  - "USER_HOME"
  - "GITHUB_TOKEN"
  deniedProcessEnvironmentVariablesSubstrings:
  - "PASS"
  - "SECRET"
  - "TOKEN"
  - "USER"
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true
  forceOverwrite: false
  licenseFactProviders:
  - type: "DefaultCustomLicenseTexts"
  - type: "DefaultLicenseTextCuration"
  - type: "SPDX"
  - type: "ScanCode"
  licenseFilePatterns:
    licenseFilenames:
    - "copying*"
    - "copyright"
    - "licence*"
    - "license*"
    - "*.licence"
    - "*.license"
    - "unlicence"
    - "unlicense"
    noticeFilenames:
    - "notice*"
    patentFilenames:
    - "patents"
    otherLicenseFilenames:
    - "readme*"
  packageConfigurationProviders:
  - type: "DefaultDir"
    id: "DefaultDir"
    enabled: true
    options: {}
  packageCurationProviders:
  - type: "DefaultFile"
    id: "DefaultFile"
    enabled: true
    options: {}
  - type: "DefaultDir"
    id: "DefaultDir"
    enabled: true
    options: {}
  - type: "OpenSourceInsightsCurationProvider"
    id: "OpenSourceInsightsCurationProvider"
    enabled: true
    options: {}
  severeIssueThreshold: "WARNING"
  severeRuleViolationThreshold: "WARNING"
  analyzer:
    allowDynamicVersions: false
    enabledPackageManagers:
    - "Bazel"
    - "Bower"
    - "Bundler"
    - "Cargo"
    - "Carthage"
    - "CocoaPods"
    - "Composer"
    - "Conan"
    - "Gleam"
    - "GoMod"
    - "GradleInspector"
    - "Maven"
    - "Mix"
    - "NPM"
    - "NuGet"
    - "OrtProjectFile"
    - "PIP"
    - "Pipenv"
    - "PNPM"
    - "Poetry"
    - "Pub"
    - "Rebar3"
    - "SBT"
    - "SpdxDocumentFile"
    - "Stack"
    - "SwiftPM"
    - "Tycho"
    - "Unmanaged"
    - "Yarn"
    - "Yarn2"
    skipExcluded: false
  advisor:
    skipExcluded: false
  downloader:
    allowMovingRevisions: false
    includedLicenseCategories: []
    skipExcluded: false
    sourceCodeOrigins:
    - "ARTIFACT"
    - "VCS"
    enablePreemptiveAuthentication: false
  scanner:
    archive:
      enabled: true
      fileStorage:
        localFileStorage:
          directory: .ort/scanner/archive
          compression: false
    skipConcluded: false
    skipExcluded: false
    includeFilesWithoutFindings: false
    detectedLicenseMapping:
      LicenseRef-scancode-agpl-generic-additional-terms: "NOASSERTION"
      LicenseRef-scancode-free-unknown: "NOASSERTION"
      LicenseRef-scancode-generic-cla: "NOASSERTION"
      LicenseRef-scancode-generic-exception: "NOASSERTION"
      LicenseRef-scancode-generic-export-compliance: "NOASSERTION"
      LicenseRef-scancode-generic-tos: "NOASSERTION"
      LicenseRef-scancode-generic-trademark: "NOASSERTION"
      LicenseRef-scancode-gpl-generic-additional-terms: "NOASSERTION"
      LicenseRef-scancode-other-copyleft: "NOASSERTION"
      LicenseRef-scancode-other-permissive: "NOASSERTION"
      LicenseRef-scancode-patent-disclaimer: "NOASSERTION"
      LicenseRef-scancode-unknown: "NOASSERTION"
      LicenseRef-scancode-unknown-license-reference: "NOASSERTION"
      LicenseRef-scancode-unknown-spdx: "NOASSERTION"
      LicenseRef-scancode-warranty-disclaimer: "NOASSERTION"
    ignorePatterns:
    - "**/*.ort.yml"
    - "**/*.spdx.yml"
    - "**/*.spdx.yaml"
    - "**/*.spdx.json"
    - "**/META-INF/DEPENDENCIES"
    - "**/META-INF/DEPENDENCIES.txt"
    - "**/META-INF/NOTICE"
    - "**/META-INF/NOTICE.txt"
    storages:
      local:
        backend:
          localFileStorage:
            directory: .ort/scanner/results
            compression: false
  reporter: {}
  notifier: {}
