---
id: "NuGet:Microsoft.Azure:Cosmos:[1.0.0,)"
source_code_origin: VCS
path_excludes:
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Sample*/**"
  reason: "TEST_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/azure-pipelines.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/changelog*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "Microsoft.Azure.Cosmos.Encryption.Custom/tests/**"
  reason: "TEST_OF"
- pattern: "Microsoft.Azure.Cosmos.Encryption/tests/**"
  reason: "TEST_OF"
- pattern: "Microsoft.Azure.Cosmos.Samples/**"
  reason: "DOCUMENTATION_OF"
- pattern: "Microsoft.Azure.Cosmos/**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "Microsoft.Azure.Cosmos/FaultInjection/tests/**"
  reason: "TEST_OF"
- pattern: "Microsoft.Azure.Cosmos/src/Resource/Scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "Microsoft.Azure.Cosmos/tests/**"
  reason: "TEST_OF"
- pattern: "Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestJsons/twitter_data/x01.txt"
  reason: "OTHER"
  comment: |
    Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestJsons/twitter_data/x01.txt due to a timeout error
- pattern: "Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestJsons/twitter_data/x03.txt"
  reason: "OTHER"
  comment: |
    Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestJsons/twitter_data/x03.txt due to a timeout error
- pattern: "Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestJsons/twitter_data/x07.txt"
  reason: "OTHER"
  comment: |
    Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestJsons/twitter_data/x07.txt due to a timeout error
