- id: "NuGet:Microsoft.NETCore:Platforms"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.NETCore:Platforms:[5.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
      Found VCS via package registry, see https://www.nuget.org/packages/microsoft.netcore.platforms.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/runtime.git"

- id: "NuGet:Microsoft.NETCore:Platforms:[6.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/Microsoft.NETCore.Platforms/src"

- id: "NuGet:Microsoft.NETCore:Platforms:[5.0.0,5.0.18]"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/pkg/Microsoft.NETCore.Platforms"

- id: "NuGet:Microsoft.NETCore:Platforms:[1.0.0,3.1.12]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/corefx.git"

- id: "NuGet:Microsoft.NETCore:Platforms:[1.0.0,3.1.12]"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "pkg/Microsoft.NETCore.Platforms"

- id: "NuGet:Microsoft.NETCore:Platforms:[5.0.0,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/runtime/blob/v5.0.0/LICENSE.TXT#L1-L23
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.NETCore.Platforms/5.0.0/license": "MIT"
