- id: "NuGet:Microsoft.NETCore:Targets"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.NETCore:Targets:5.0.0"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/Microsoft.NETCore.Targets/5.0.0
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/runtime.git"

- id: "NuGet:Microsoft.NETCore:Targets:5.0.0"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/pkg/Microsoft.NETCore.Targets"

- id: "NuGet:Microsoft.NETCore:Targets:[1.0.0,3.1.0]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/Microsoft.NETCore.Targets/3.1.0.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/corefx.git"

- id: "NuGet:Microsoft.NETCore:Targets:[1.0.0,3.1.0]"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "pkg/Microsoft.NETCore.Targets"

- id: "NuGet:Microsoft.NETCore:Targets:1.1.0"
  curations:
    comment: |
      Map declared license based on
      https://scancode-licensedb.aboutcode.org/ms-net-library-2016-05.html.
      https://web.archive.org/web/20170611153216/http://www.microsoft.com/net/dotnet_library_license.htm.
      https://nuget.info/packages/Microsoft.NETCore.Targets/1.1.0.
    declared_license_mapping:
      "http://go.microsoft.com/fwlink/?LinkId=329770": "LicenseRef-scancode-ms-net-library-2016-05"