---
id: "NuGet::DnsClient:(,1.7.0]"
source_code_origin: "VCS"
path_excludes:
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*sample*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "samples/**"
  reason: "EXAMPLE_OF"
