- id: "NuGet:AWSSDK.IoT1ClickProjects:CoreCLR:[3.3.280,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/IoT1ClickProjects"
