- id: "NuGet:runtime.debian:8-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:runtime.debian:8-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/corefx.git"

- id: "NuGet:runtime.debian:8-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Native/Unix/System.Security.Cryptography.Native"

- id: "NuGet:runtime.debian:8-x64.runtime.native.System.Security.Cryptography.OpenSsl:4.3.2"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.2.
    vcs:
      revision: "a77147de09767c600d1e1d071526f3ef76358c59"
