---
id: "NuGet:Microsoft.IdentityModel:Protocols:(,8.9.0]"
source_code_origin: "VCS"
path_excludes:
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*bench*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CHANGELOG*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Tools/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build*.sh"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build/**"
  reason: "BUILD_TOOL_OF"
- pattern: "Contributing.md"
  reason: "DOCUMENTATION_OF"
  comment: |
    Contributing.md is excluded from assessment here because the file is not applicable in the present case as the package is not considered in contribution context
