- id: "NuGet:System.Security:Cryptography"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/System.Security.Cryptography"
