- id: "NuGet:System.Security:Permissions:[5.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/System.Security.Permissions"

- id: "NuGet:System.Security:Permissions:[6.0.0,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/runtime/blob/v6.0.0/LICENSE.TXT.
    declared_license_mapping:
      "https://www.nuget.org/packages/System.Security.Permissions/6.0.0/license": "MIT"
