- id: "NuGet:System.Security:Principal.Windows:[5.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/System.Security.Principal.Windows"

- id: "NuGet:System.Security:Principal.Windows:[5.0.0,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/runtime/blob/v5.0.0/LICENSE.TXT.
    declared_license_mapping:
      "https://www.nuget.org/packages/System.Security.Principal.Windows/5.0.0/license": "MIT"
