- id: "NuGet:System.ComponentModel:EventBasedAsync:[5.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/libraries/System.ComponentModel.EventBasedAsync"
