---
id: "PyPI::numpy:(,2.5.1]"
path_excludes:
- pattern: "**/*.bazel"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*.pdf"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*bench*/**"
  reason: "TEST_OF"
- pattern: "**/*doc*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*example*/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.bazelrc"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.circleci/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.clang-format"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.devcontainer/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/.mailmap"
  reason: "OTHER"
- pattern: "**/.spin/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/BUILD"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CMakeLists.txt"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CODE_OF_CONDUCT.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CONTRIBUTING"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/CONTRIBUTING.rst"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Makefile*"
  reason: "BUILD_TOOL_OF"
- pattern: "**/PKG-INFO"
  reason: "DATA_FILE_OF"
  comment: |
    Package metadata file generated during build. Not included of the distributed runtime artifact.
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/azure-pipelines.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/branding/**"
  reason: "DOCUMENTATION_OF"
- pattern: "**/changelog*"
  reason: "DOCUMENTATION_OF"
- pattern: "**/ci/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/cmake/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/mesonbuild/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/pyproject.toml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/scripts/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/setup.cfg"
  reason: "BUILD_TOOL_OF"
- pattern: "**/setup.py"
  reason: "BUILD_TOOL_OF"
- pattern: "**/test_*.c"
  reason: "TEST_OF"
- pattern: "**/tools/**"
  reason: "BUILD_TOOL_OF"
