- id: "NuGet:AWSSDK.ResourceGroups:CoreCLR:[3.3.200,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/ResourceGroups"
