- id: "NuGet:AWSSDK.IoTThingsGraph:PCL:[3.3.520,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/IoTThingsGraph"
