- id: "NuGet:Swashbuckle.AspNetCore:SwaggerUI:[10.2.1,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v10.2.1/LICENSE.
    declared_license_mapping:
      "https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerUI/10.2.1/license": "MIT"
      "https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerUI/10.2.3/license": "MIT"