- id: "NuGet:Grpc.Core:Api"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Grpc.Core:Api:[2.65.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/grpc/grpc-dotnet.git"

- id: "NuGet:Grpc.Core:Api:[2.65.0,)"
  curations:
    comment: |
      Package resides in its own directory within repository.
    vcs:
      path: "src/Grpc.Core.Api"

- id: "NuGet:Grpc.Core:Api:[2.65.0,)"
  curations:
    comment: |
      Mapping declared license based on
      https://github.com/grpc/grpc-dotnet/blob/v2.65.0/LICENSE
    declared_license_mapping:
      "https://www.nuget.org/packages/Grpc.Core.Api/2.65.0/license": "Apache-2.0"