---
id: "NuGet:Microsoft.Extensions:Hosting:8.0.1"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime"
  revision: "81cabf2857a01351e5ab578947c7403a5b128ad1"
path_excludes:
- pattern: "tests/**"
  reason: "TEST_OF"
license_finding_curations:
- path: "src/Internal/ApplicationLifetime.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/ConfigureContainerAdapter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/ConsoleLifetime.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/ConsoleLifetime.netcoreapp.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/ConsoleLifetime.notnetcoreapp.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ConsoleLifetimeOptions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/Host.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Host.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostApplicationBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostApplicationBuilderSettings.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostBuilder.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostBuilder.netcoreapp.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostBuilder.notnetcoreapp.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostOptions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/HostingEnvironment.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/HostingHostBuilderExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/HostingLoggerExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/IConfigureContainerAdapter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/IServiceFactoryAdapter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/LoggerEventIds.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Microsoft.Extensions.Hosting.Forwards.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "ref/Microsoft.Extensions.Hosting.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/NullLifetime.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/PACKAGE.md"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/Internal/ServiceFactoryAdapter.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"