---
id: "NuGet:Refit:HttpClientFactory:[7.2.22,10.2.0]"
source_code_origin: "VCS"
path_excludes:
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*Bench*/**"
  reason: "TEST_OF"
- pattern: "**/*Test*/**"
  reason: "TEST_OF"
- pattern: "**/*example*/**"
  reason: "EXAMPLE_OF"
- pattern: "**/*sample*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CODE_OF_CONDUCT.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/Dockerfile"
  reason: "BUILD_TOOL_OF"
- pattern: "Directory.Build.props"
  reason: "BUILD_TOOL_OF"
