- id: "NuGet:Azure.IoT:ModelsRepository"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/modelsrepository/Azure.IoT.ModelsRepository"
