- id: "NuGet:AWSSDK.GlobalAccelerator:CoreCLR:[3.3.415,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/GlobalAccelerator"
