---
id: "NuGet:Azure.Security:KeyVault.Certificates:[1.0.0,)"
source_code_origin: VCS
path_excludes:
  - pattern: "sdk/core/Azure.Core/tests/common/TestData/ResourceProviderData/ResourceProviderData-Collapsed.json"
    reason: "OTHER"
    comment: "Excluded due to ScanCode timeout (known large test data file)"
  - pattern: "sdk/core/System.ClientModel/tests/client/TestData/ResourceProviderData/ResourceProviderData-Collapsed.json"
    reason: "OTHER"
    comment: "Excluded due to ScanCode timeout (known large test data file)"
  - pattern: "sdk/compute/Microsoft.Azure.Management.Compute/tests/**"
    reason: "TEST_OF"
  - pattern: "sdk/storage/Azure.Storage.Blobs/tests/**"
    reason: "TEST_OF"
  - pattern: "sdk/azurestack/Microsoft.AzureStack.Management.AzureBridge.Admin/tests/**"
    reason: "TEST_OF"
  - pattern: "sdk/azurestack/Microsoft.AzureStack.Management.Gallery.Admin/tests/**"
    reason: "TEST_OF"
  - pattern: "sdk/schemaregistry/Azure.Data.SchemaRegistry/samples/**"
    reason: "EXAMPLE_OF"
  - pattern: "samples/**"
    reason: "EXAMPLE_OF"
  - pattern: "sdk/resourcemanager/Azure.ResourceManager/docs/**"
    reason: "DOCUMENTATION_OF"
  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
  - pattern: "sdk/eventhub/Azure.Messaging.EventHubs/samples/**"
    reason: "EXAMPLE_OF"
  - pattern: "eng/templates/**"
    reason: "EXAMPLE_OF"
  - pattern: "tools/bootstrapTools/taskBinaries/Microsoft.Build.Tasks.Core.dll"
    reason: "BUILD_TOOL_OF"
  - pattern: "tools/NuGet.exe"
    reason: "BUILD_TOOL_OF"
  - pattern: "tools/NugetExe/NuGet.exe"
    reason: "BUILD_TOOL_OF"
  - pattern: "sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/**"
    reason: "EXAMPLE_OF"
  - pattern: "sdk/core/Azure.Core/tests/**"
    reason: "TEST_OF"
  - pattern: "sdk/core/System.ClientModel/tests/**"
    reason: "TEST_OF"
