- id: "NuGet:System:Memory"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:System:Memory:(,4.5.5]"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/system.memory/.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/corefx.git"

- id: "NuGet:System:Memory:(,4.5.5]"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/System.Memory/src"

- id: "NuGet:System:Memory:4.5.4"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/System.Memory/4.5.4 and
      https://github.com/dotnet/corefx/commit/7601f4f6225089ffb291dc7d58293c7bbf5c5d4f.
    vcs:
      revision: "7601f4f6225089ffb291dc7d58293c7bbf5c5d4f"

- id: "NuGet:System:Memory:4.5.5"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/System.Memory/4.5.5 and
      https://github.com/dotnet/corefx/commit/04944b999f540d3f1068208c351716a8954e4c2b.
    vcs:
      revision: "04944b999f540d3f1068208c351716a8954e4c2b"