- id: "NuGet:OpenTelemetry.Api:ProviderBuilderExtensions"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:OpenTelemetry.Api:ProviderBuilderExtensions"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable from internal package registries (e.g., Artifactory).
      Found VCS via package registry, see https://www.nuget.org/packages/OpenTelemetry.Api.ProviderBuilderExtensions.
    vcs:
      type: "Git"
      url: "https://github.com/open-telemetry/opentelemetry-dotnet.git"

- id: "NuGet:OpenTelemetry.Api:ProviderBuilderExtensions"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/OpenTelemetry.Api.ProviderBuilderExtensions"

- id: "NuGet:OpenTelemetry.Api:ProviderBuilderExtensions"
  curations:
    comment: |
      Map declared license based on
      https://github.com/open-telemetry/opentelemetry-dotnet/blob/core-1.16.0/LICENSE.TXT#L1-L201.
    declared_license_mapping:
      "https://www.nuget.org/packages/OpenTelemetry.Api.ProviderBuilderExtensions/1.16.0/license": "Apache-2.0"
      "https://www.nuget.org/packages/OpenTelemetry.Api.ProviderBuilderExtensions/1.17.0/license": "Apache-2.0"