---
id: "NuGet:Microsoft.AspNetCore:Mvc.Versioning:(,5.1.0]"
path_excludes:
- pattern: "**/*.csproj"
  reason: "BUILD_TOOL_OF"
- pattern: "**/*sample*/**"
  reason: "TEST_OF"
- pattern: "**/*test*/**"
  reason: "TEST_OF"
- pattern: "**/.editorconfig"
  reason: "OTHER"
- pattern: "**/.github/**"
  reason: "BUILD_TOOL_OF"
- pattern: "**/CONTRIBUTING.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/SECURITY.md"
  reason: "DOCUMENTATION_OF"
- pattern: "**/azure-pipelines.yml"
  reason: "BUILD_TOOL_OF"
- pattern: "**/build/**"
  reason: "BUILD_TOOL_OF"
