- id: "NuGet:Microsoft.IdentityModel:Protocols.OpenIdConnect:[5.3.0,)"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.IdentityModel:Protocols.OpenIdConnect:[5.3.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet.git"

- id: "NuGet:Microsoft.IdentityModel:Protocols.OpenIdConnect:[5.3.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/Microsoft.IdentityModel.Protocols.OpenIdConnect"

- id: "NuGet:Microsoft.IdentityModel:Protocols.OpenIdConnect:[5.3.0,)"
  curations:
    comment: |
      Map declared license based on
      https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/c94c7fc/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/5.3.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/6.35.0/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/8.19.2/license": "MIT"
