- id: "NuGet:Azure.ResourceManager:Advisor"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/advisor/Azure.ResourceManager.Advisor"
