- id: "NuGet:Azure.ResourceManager:AgFoodPlatform"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/agrifood/Azure.ResourceManager.AgFoodPlatform"
