- id: "NuGet:Azure.ResourceManager:AlertsManagement"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/alertsmanagement/Azure.ResourceManager.AlertsManagement"
