- id: "NuGet:Azure.ResourceManager:Analysis"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/analysisservices/Azure.ResourceManager.Analysis"
