- id: "NuGet:Azure.ResourceManager:AppComplianceAutomation"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/appcomplianceautomation/Azure.ResourceManager.AppComplianceAutomation"
