- id: "NuGet:Azure.ResourceManager:ApplicationInsights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/applicationinsights/Azure.ResourceManager.ApplicationInsights"
