- id: "NuGet:Azure.ResourceManager:AppPlatform"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/appplatform/Azure.ResourceManager.AppPlatform"
