- id: "NuGet:Azure.ResourceManager:ArcScVmm"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/arc-scvmm/Azure.ResourceManager.ArcScVmm"
