- id: "NuGet:Azure.ResourceManager:Attestation"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/attestation/Azure.ResourceManager.Attestation"
