- id: "NuGet:Azure.ResourceManager:Authorization"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/authorization/Azure.ResourceManager.Authorization"
