- id: "NuGet:Azure.ResourceManager:Automation"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/automation/Azure.ResourceManager.Automation"
