- id: "NuGet:Azure.ResourceManager:Automanage"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/automanage/Azure.ResourceManager.Automanage"
