- id: "NuGet:Azure.ResourceManager:BillingBenefits"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/billingbenefits/Azure.ResourceManager.BillingBenefits"
