- id: "NuGet:Azure.ResourceManager:ChangeAnalysis"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/changeanalysis/Azure.ResourceManager.ChangeAnalysis"
