- id: "NuGet:Azure.ResourceManager:CognitiveServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/cognitiveservices/Azure.ResourceManager.CognitiveServices"
