- id: "NuGet:Azure.ResourceManager:Communication"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/communication/Azure.ResourceManager.Communication"
