- id: "NuGet:Azure.ResourceManager:Confluent"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/confluent/Azure.ResourceManager.Confluent"
