- id: "NuGet:Azure.ResourceManager:ConfidentialLedger"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/confidentialledger/Azure.ResourceManager.ConfidentialLedger"
