- id: "NuGet:Azure.ResourceManager:ConnectedVMwarevSphere"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/connectedvmwarevsphere/Azure.ResourceManager.ConnectedVMwarevSphere"
