- id: "NuGet:Azure.ResourceManager:Consumption"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/consumption/Azure.ResourceManager.Consumption"
