- id: "NuGet:Azure.ResourceManager:ContainerRegistry"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/containerregistry/Azure.ResourceManager.ContainerRegistry"
