- id: "NuGet:Azure.ResourceManager:ContainerInstance"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/containerinstance/Azure.ResourceManager.ContainerInstance"
