- id: "NuGet:Azure.ResourceManager:CosmosDB"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/cosmosdb/Azure.ResourceManager.CosmosDB"
