- id: "NuGet:Azure.ResourceManager:CustomerInsights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/customer-insights/Azure.ResourceManager.CustomerInsights"
