- id: "NuGet:Azure.ResourceManager:DataLakeAnalytics"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datalake-analytics/Azure.ResourceManager.DataLakeAnalytics"
