- id: "NuGet:Azure.ResourceManager:DataBoxEdge"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/databoxedge/Azure.ResourceManager.DataBoxEdge"
