- id: "NuGet:Azure.ResourceManager:DataMigration"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datamigration/Azure.ResourceManager.DataMigration"
