- id: "NuGet:Azure.ResourceManager:DataProtectionBackup"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup"
