- id: "NuGet:Azure.ResourceManager:DataShare"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/datashare/Azure.ResourceManager.DataShare"
