- id: "NuGet:Azure.ResourceManager:DesktopVirtualization"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization"
