- id: "NuGet:Azure.ResourceManager:DeviceUpdate"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/deviceupdate/Azure.ResourceManager.DeviceUpdate"
