- id: "NuGet:Azure.ResourceManager:DevTestLabs"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/devtestlabs/Azure.ResourceManager.DevTestLabs"
