- id: "NuGet:Azure.ResourceManager:Dynatrace"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/dynatrace/Azure.ResourceManager.Dynatrace"
