- id: "NuGet:Azure.ResourceManager:EdgeOrder"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/edgeorder/Azure.ResourceManager.EdgeOrder"
