- id: "NuGet:Azure.ResourceManager:Elastic"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/elastic/Azure.ResourceManager.Elastic"
