- id: "NuGet:Azure.ResourceManager:EventHubs"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/eventhub/Azure.ResourceManager.EventHubs"
