- id: "NuGet:Azure.ResourceManager:FrontDoor"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/frontdoor/Azure.ResourceManager.FrontDoor"
