- id: "NuGet:Azure.ResourceManager:Grafana"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/grafana/Azure.ResourceManager.Grafana"
