- id: "NuGet:Azure.ResourceManager:GuestConfiguration"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/guestconfiguration/Azure.ResourceManager.GuestConfiguration"
