- id: "NuGet:Azure.ResourceManager:Hci"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/azurestackhci/Azure.ResourceManager.Hci"
