- id: "NuGet:Azure.ResourceManager:HDInsight"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/hdinsight/Azure.ResourceManager.HDInsight"
