- id: "NuGet:Azure.ResourceManager:Insights"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/insights/Azure.ResourceManager.Insights"
