- id: "NuGet:Azure.ResourceManager:MachineLearningServices"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/machinelearningservices/Azure.ResourceManager.MachineLearningServices"
