- id: "NuGet:Azure.ResourceManager:Network"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/network/Azure.ResourceManager.Network"
