- id: "NuGet:AWSSDK.SecurityToken:Unity:[3.1.46,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/SecurityToken"
