- id: "NuGet:AWSSDK.CostAndUsageReport:PCL:[3.3.38,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/CostAndUsageReport"
