---
id: "NuGet:Microsoft.Extensions:Options.ConfigurationExtensions:8.0.0"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime.git"
  revision: "5535e31a712343a63f5d7d796cd874e563e5ac14"
path_excludes:
- pattern: "src/tests/**"
  reason: "TEST_OF"
- pattern: "src/installer/pkg/LICENSE-MSFT.TXT"
  reason: "BUILD_TOOL_OF"
- pattern: "src/libraries/System.Reflection.Metadata/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Net.Sockets/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Runtime/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Private.Xml.Linq/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.ServiceModel.Syndication/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Text.RegularExpressions/tests/**"
  reason: "TEST_OF"
- pattern: "src/native/external/libunwind/doc/**"
  reason: "DOCUMENTATION_OF"
- pattern: "docs/**"
  reason: "DOCUMENTATION_OF"
- pattern: "src/native/external/libunwind/doc/**"
  reason: "DOCUMENTATION_OF"
license_finding_curations:
- path: "src/ConfigurationChangeTokenSource.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/ConfigureFromConfigurationOptions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "ref/Microsoft.Extensions.Options.ConfigurationExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/NamedConfigureFromConfigurationOptions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/OptionsBuilderConfigurationExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/OptionsConfigurationServiceCollectionExtensions.cs"
  start_lines: "2"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/PACKAGE.md"
  start_lines: "145"
  line_count: 1
  detected_license: "NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/LicFileLicenseProvider.cs"
  start_lines: "1"
  line_count: 109
  detected_license: "MIT AND LicenseRef-scancode-proprietary-license"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/XmlLicenseTransform.cs"
  start_lines: "1"
  line_count: 18
  detected_license: "MIT AND LicenseRef-scancode-proprietary-license"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/native/external/zlib/FAQ"
  start_lines: "167"
  line_count: 1
  detected_license: "GPL-1.0-or-later"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/mono/mono/mini/THIRD-PARTY-NOTICES.TXT"
  start_lines: "1"
  line_count: 17
  detected_license: "GPL-1.0-or-later"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "PATENTS.TXT"
  start_lines: "1"
  line_count: 46
  detected_license: "LicenseRef-scancode-ms-patent-promise"
  concluded_license: "LicenseRef-scancode-ms-patent-promise"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-ms-patent-promise"
- path: "CONTRIBUTING.md"
  start_lines: "146"
  line_count: 16
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/libraries/System.Text.Json/roadmap/images/core-components.txt"
  start_lines: "1"
  line_count: 4
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.Text.Json/roadmap/images/higher-level-components.txt"
  start_lines: "1"
  line_count: 4
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/mono/mono/mini/mini-posix.c"
  start_lines: "12"
  line_count: 2
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/mono/mono/mini/mini-windows.c"
  start_lines: "11"
  line_count: 2
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/native/external/zlib-intel/inffast.c"
  start_lines: "3"
  line_count: 21
  detected_license: "Zlib AND NOASSERTION"
  concluded_license: "Zlib"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/native/external/zlib/inffast.c"
  start_lines: "3"
  line_count: 21
  detected_license: "Zlib AND NOASSERTION"
  concluded_license: "Zlib"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/installer/pkg/THIRD-PARTY-NOTICES.TXT"
  start_lines: "1"
  line_count: 1815
  detected_license: "Apache-2.0 AND BSD-3-Clause AND LicenseRef-scancode-unicode AND Zlib AND MIT AND LicenseRef-scancode-iso-8879 AND BSD-2-Clause AND W3C-20150513 AND LicenseRef-scancode-public-domain AND LicenseRef-scancode-ietf AND HP-1989 AND NCSA AND CC0-1.0 AND CC0-1.0 AND LicenseRef-scancode-public-domain AND MIT AND BSD-4-Clause-UC AND MIT AND LZMA-SDK-9.22 AND BSD-2-Clause AND MIT AND Apache-2.0 AND MIT AND MIT AND NOASSERTION WITH fmt-exception AND NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "THIRD-PARTY-NOTICES.TXT"
  start_lines: "1"
  line_count: 1269
  detected_license: "Apache-2.0 AND BSD-3-Clause AND LicenseRef-scancode-unicode AND Zlib AND MIT AND LicenseRef-scancode-iso-8879 AND BSD-2-Clause AND W3C-20150513 AND LicenseRef-scancode-public-domain AND LicenseRef-scancode-ietf AND HP-1989 AND NCSA AND CC0-1.0 AND NOASSERTION AND BSD-4-Clause-UC AND MIT AND NOASSERTION WITH fmt-exception"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/mono/mono/mini/bench.cs"
  start_lines: "5"
  line_count: 61
  detected_license: "MIT AND GPL-1.0-or-later"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.Private.Xml/src/Utils/DTDs/RSS091/original/rss-0.91.dtd"
  start_lines: "48"
  line_count: 3
  detected_license: "LicenseRef-scancode-iso-8879"
  concluded_license: "LicenseRef-scancode-iso-8879"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-iso-8879"
- path: "src/libraries/System.Private.Xml/src/Utils/DTDs/XHTML10/original/xhtml-lat1.ent"
  start_lines: "2"
  line_count: 3
  detected_license: "LicenseRef-scancode-iso-8879"
  concluded_license: "LicenseRef-scancode-iso-8879"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-iso-8879"
- path: "src/libraries/System.Private.Xml/src/Utils/DTDs/XHTML10/original/xhtml-special.ent"
  start_lines: "11"
  line_count: 3
  detected_license: "LicenseRef-scancode-iso-8879"
  concluded_license: "LicenseRef-scancode-iso-8879"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-iso-8879"
- path: "src/libraries/System.Private.Xml/src/Utils/DTDs/XHTML10/original/xhtml-symbol.ent"
  start_lines: "11"
  line_count: 3
  detected_license: "LicenseRef-scancode-iso-8879"
  concluded_license: "LicenseRef-scancode-iso-8879"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-iso-8879"