---
id: "NuGet:Microsoft.Extensions:Hosting.Abstractions:8.0.1"
vcs:
  type: "Git"
  url: "https://github.com/dotnet/runtime.git"
  revision: "81cabf2857a01351e5ab578947c7403a5b128ad1"
path_excludes:
- pattern: "src/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Reflection.Metadata/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Net.Sockets/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Runtime/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Private.Xml.Linq/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.ServiceModel.Syndication/tests/**"
  reason: "TEST_OF"
- pattern: "src/libraries/System.Text.RegularExpressions/tests/**"
  reason: "TEST_OF"
- pattern: "src/native/external/libunwind/doc/**"
  reason: "DOCUMENTATION_OF"
- pattern: "docs/**"
  reason: "DOCUMENTATION_OF"
license_finding_curations:
- path: "src/native/external/libunwind/scripts/qemu-test-driver"
  start_lines: "8"
  line_count: 19
  detected_license: "GPL-2.0-or-later WITH Autoconf-exception-generic"
  concluded_license: "GPL-2.0-or-later WITH Autoconf-exception-generic"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as GPL-2.0-or-later WITH Autoconf-exception-generic"
- path: "src/native/external/zlib/FAQ"
  start_lines: "166"
  line_count: 1
  detected_license: "GPL-1.0-or-later"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/mono/mono/mini/THIRD-PARTY-NOTICES.TXT"
  start_lines: "1"
  line_count: 17
  detected_license: "GPL-1.0-or-later"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/native/external/llvm-libunwind/LICENSE.TXT"
  start_lines: "208"
  line_count: 14
  detected_license: "GPL-2.0-only"
  concluded_license: "Apache-2.0 WITH LLVM-exception"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/native/external/llvm-libunwind/LICENSE.TXT"
  start_lines: "249"
  line_count: 40
  detected_license: "GPL-2.0-only"
  concluded_license: "NCSA"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/mono/mono/utils/memcheck.h"
  start_lines: "5"
  line_count: 2
  detected_license: "GPL-2.0-only"
  concluded_license: "GPL-2.0-only"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as GPL-2.0-only"
- path: "src/mono/mono/utils/valgrind.h"
  start_lines: "5"
  line_count: 2
  detected_license: "GPL-2.0-only"
  concluded_license: "GPL-2.0-only"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as GPL-2.0-only" 
- path: "LICENSE.TXT"
  start_lines: "1"
  line_count: 21
  detected_license: "LicenseRef-scancode-unknown-license-reference"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/native/external/libunwind/COPYING"
  start_lines: "1"
  line_count: 21
  detected_license: "LicenseRef-scancode-free-unknown"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/native/external/zlib/README"
  start_lines: "92"
  line_count: 11
  detected_license: "LicenseRef-scancode-free-unknown"
  concluded_license: "Zlib"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "README.md"
  start_lines: "77"
  line_count: 1
  detected_license: "LicenseRef-scancode-free-unknown"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/LicFileLicenseProvider.cs"
  start_lines: "1"
  line_count: 109
  detected_license: "MIT AND LicenseRef-scancode-proprietary-license"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/XmlLicenseTransform.cs"
  start_lines: "1"
  line_count: 18
  detected_license: "MIT AND LicenseRef-scancode-proprietary-license"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "PATENTS.TXT"
  start_lines: "1"
  line_count: 46
  detected_license: "LicenseRef-scancode-ms-patent-promise"
  concluded_license: "LicenseRef-scancode-ms-patent-promise"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-ms-patent-promise"
- path: "src/installer/pkg/LICENSE-MSFT.TXT"
  start_lines: "1"
  line_count: 63
  detected_license: "LicenseRef-scancode-ms-net-library-2016-05"
  concluded_license: "LicenseRef-scancode-ms-net-library-2016-05"
  reason: "DOCUMENTATION_OF"
  comment: "Upon Investigation we found license as LicenseRef-scancode-ms-net-library-2016-05"
- path: "CONTRIBUTING.md"
  start_lines: "146"
  line_count: 16
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/libraries/System.Text.Json/roadmap/images/core-components.txt"
  start_lines: "1"
  line_count: 4
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/libraries/System.Text.Json/roadmap/images/higher-level-components.txt"
  start_lines: "1"
  line_count: 4
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/mono/mono/mini/mini-posix.c"
  start_lines: "12"
  line_count: 2
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/mono/mono/mini/mini-windows.c"
  start_lines: "11"
  line_count: 2
  detected_license: "MIT AND NOASSERTION"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"
- path: "src/native/external/zlib-intel/inffast.c"
  start_lines: "3"
  line_count: 21
  detected_license: "Zlib AND NOASSERTION"
  concluded_license: "Zlib"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/native/external/zlib/inffast.c"
  start_lines: "3"
  line_count: 21
  detected_license: "Zlib AND NOASSERTION"
  concluded_license: "Zlib"
  reason: "REFERENCE"
  comment: "True Positive"
- path: "src/installer/pkg/THIRD-PARTY-NOTICES.TXT"
  start_lines: "1"
  line_count: 1815
  detected_license: "Apache-2.0 AND BSD-3-Clause AND LicenseRef-scancode-unicode AND Zlib AND MIT AND LicenseRef-scancode-iso-8879 AND BSD-2-Clause AND W3C-20150513 AND LicenseRef-scancode-public-domain AND LicenseRef-scancode-ietf AND HP-1989 AND NCSA AND CC0-1.0 AND CC0-1.0 AND LicenseRef-scancode-public-domain AND MIT AND BSD-4-Clause-UC AND MIT AND LZMA-SDK-9.22 AND BSD-2-Clause AND MIT AND Apache-2.0 AND MIT AND MIT AND NOASSERTION WITH fmt-exception AND NOASSERTION"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "THIRD-PARTY-NOTICES.TXT"
  start_lines: "1"
  line_count: 1269
  detected_license: "Apache-2.0 AND BSD-3-Clause AND LicenseRef-scancode-unicode AND Zlib AND MIT AND LicenseRef-scancode-iso-8879 AND BSD-2-Clause AND W3C-20150513 AND LicenseRef-scancode-public-domain AND LicenseRef-scancode-ietf AND HP-1989 AND NCSA AND CC0-1.0 AND NOASSERTION AND BSD-4-Clause-UC AND MIT AND NOASSERTION WITH fmt-exception"
  concluded_license: "NONE"
  reason: "INCORRECT"
  comment: "False Positive"
- path: "src/mono/mono/mini/bench.cs"
  start_lines: "5"
  line_count: 61
  detected_license: "MIT AND GPL-1.0-or-later"
  concluded_license: "MIT"
  reason: "DOCUMENTATION_OF"
  comment: "True Positive"