- id: "NuGet:AWSSDK.RDSDataService:CoreCLR:[3.3.412,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "sdk/src/Services/RDSDataService"
