- id: "NuGet:Microsoft.EntityFrameworkCore:Sqlite.Core"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.EntityFrameworkCore:Sqlite.Core:[10.0.0,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/dotnet.git"

- id: "NuGet:Microsoft.EntityFrameworkCore:Sqlite.Core:[10.0.0,)"
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/efcore/src/EFCore.Sqlite.Core"

- id: "NuGet:Microsoft.EntityFrameworkCore:Sqlite.Core:[2.0.0,10.0.0["
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/efcore.git"

- id: "NuGet:Microsoft.EntityFrameworkCore:Sqlite.Core:[2.0.0,10.0.0["
  curations:
    comment: |
      Package resides in its own directory within code repository.
    vcs:
      path: "src/EFCore.Sqlite.Core"

- id: "NuGet:Microsoft.EntityFrameworkCore:Sqlite.Core"
  curations:
    comment: |
      Map declared license based on
      https://github.com/dotnet/efcore/blob/v7.0.20/LICENSE.txt#L1-L23.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite.Core/7.0.20/license": "MIT"