- id: "NuGet:Microsoft.EntityFrameworkCore:SqlServer"
  curations:
    comment: |
      Enforce scanning the code repository because the source artifact does not contain all corresponding source files.
    source_code_origins: [VCS]

- id: "NuGet:Microsoft.EntityFrameworkCore:SqlServer:[2.0.1,)"
  curations:
    comment: |
      Package code repository location is not declared, or the metadata is unavailable in internal Artifactory.
    vcs:
      type: "Git"
      url: "https://github.com/dotnet/efcore.git"

- id: "NuGet:Microsoft.EntityFrameworkCore:SqlServer:[2.0.1,)"
  curations:
    comment: |
      Package resides in its own directory within repository.
    vcs:
      path: "src/EFCore.SqlServer"

- id: "NuGet:Microsoft.EntityFrameworkCore:SqlServer:7.0.20"
  curations:
    comment: |
      Package code repository missing version tag for this release.
      The exact commit for this version could not be determined.
      Using the closest commit based on the package release date and/or code repository filepath history, see
      https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/7.0.20 and
      https://github.com/dotnet/efcore/commit/136f129ddca49729a24f0e65465fc638bd584c70.
    vcs:
      revision: "136f129ddca49729a24f0e65465fc638bd584c70"

- id: "NuGet:Microsoft.EntityFrameworkCore:SqlServer:[7.0.20,)"
  curations:
    comment: |
      Mapping declared license based on
      https://github.com/dotnet/efcore/blob/v7.0.20/LICENSE.txt#L1-L23
      https://github.com/dotnet/efcore/blob/v8.0.23/LICENSE.txt.
    declared_license_mapping:
      "https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/7.0.20/license": "MIT"
      "https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.23/license": "MIT"